### ISSUE TITLE
The .info file is missing type attribute

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/seckit#1]
Simple first issue, the .info file is missing type attribute `type = module`.

**Comment by laryn** [comment]
Oops! Do you want to PR that?

**Comment by oadaeh** [comment]
Is PR a verb now?

**Comment by laryn** [comment]
Good question. I’ll dictionary that to see.

**Comment by laryn** [comment]
Too late @izmeez I did it. ;)

**Comment by izmeez** [comment]
Thanks.
